// script.js (versão com localStorage)

const frases = [
    "O sucesso é a soma de pequenos esforços repetidos diariamente.",
    "A disciplina é a ponte entre metas e realizações.",
    "Não espere por oportunidades, crie-as.",
    "O maior obstáculo é o que você cria na sua mente.",
    "Transforme desafios em degraus para o crescimento.",
    "Faça hoje o que os outros não fazem, para ter amanhã o que os outros não têm.",
    "A produtividade não é um acidente, é um compromisso com a excelência.",
    "O primeiro passo para o sucesso é a organização.",
    "Se for para fazer, faça bem-feito.",
    "Não adie para amanhã o que pode fazer hoje.",
    "A excelência é um hábito, não um ato.",
    "O tempo é o seu recurso mais valioso. Use-o com sabedoria.",
    "O progresso, não a perfeição, é o que importa.",
    "Uma meta sem um plano é apenas um desejo.",
    "Seja a pessoa que faz as coisas acontecerem.",
    "A melhor forma de prever o futuro é criá-lo.",
    "Mantenha os seus olhos nas estrelas e os seus pés no chão.",
    "Pequenas melhorias diárias levam a grandes resultados com o tempo.",
    "Concentre-se no processo, e o resultado virá.",
    "A sua agenda reflete as suas prioridades.",
    "Aja com urgência, mas sem pressa.",
    "O sucesso começa com a decisão de tentar.",
    "O esforço de hoje é a recompensa de amanhã.",
    "Cada dia é uma nova chance para fazer melhor.",
    "Mantenha o foco, mesmo quando ninguém estiver olhando.",
    "A consistência é mais importante que a perfeição.",
    "A sua dedicação é a nossa inspiração.",
    "A melhoria contínua é o caminho para a excelência.",
    "Se não puder fazer grandes coisas, faça pequenas coisas de forma grandiosa.",
    "O seu trabalho faz a diferença.",
    "Juntos, somos mais fortes e mais criativos.",
    "O sucesso da equipe é a prioridade.",
    "Nenhum de nós é tão bom quanto todos nós juntos.",
    "A melhor forma de prever o futuro é criá-lo juntos.",
    "Celebre as vitórias dos seus colegas.",
    "O trabalho em equipe divide a tarefa e multiplica o sucesso.",
    "A colaboração é a chave para o sucesso duradouro.",
    "Uma equipe forte não se forma por coincidência, mas por intenção.",
    "Conecte-se com as pessoas, não com as tarefas.",
    "O respeito mútuo é a base de uma equipe vencedora.",
    "O sucesso é o resultado de uma equipe que trabalha em harmonia.",
    "A união faz a força.",
    "Ajude o seu colega a brilhar. O sucesso dele é o seu também.",
    "A confiança é o alicerce de uma equipe de sucesso.",
    "Todos têm um papel importante. Valorize cada contribuição.",
    "A comunicação é a chave para o trabalho em equipe.",
    "Compartilhe o conhecimento para crescerem juntos.",
    "O verdadeiro espírito de equipe está em ajudar uns aos outros a ter sucesso.",
    "O sucesso é ainda melhor quando é compartilhado.",
    "O sucesso de um é o sucesso de todos.",
    "Um bom time transforma problemas em oportunidades.",
    "Pessoas que se ajudam, vencem juntas.",
    "A cooperação é a convicção de que ninguém pode chegar lá sozinho.",
    "A diversidade de ideias é o nosso maior ativo.",
    "Apoie os seus colegas. Juntos, somos invencíveis.",
    "Ninguém pode fazer tudo, mas todos podem fazer alguma coisa.",
    "Uma equipe é como uma família, onde cada membro é fundamental.",
    "Acredite no potencial dos seus colegas.",
    "O trabalho em equipe é a capacidade de trabalhar em conjunto em direção a uma visão comum.",
    "Lembre-se, somos uma equipe.",
    "Não tenha medo de errar. Tenha medo de não tentar.",
    "A inovação distingue um líder de um seguidor.",
    "Pense fora da caixa. Não há caixa.",
    "Ouse ser diferente. Ouse ser inovador.",
    "A única maneira de fazer um ótimo trabalho é amar o que você faz.",
    "A criatividade é a inteligência se divertindo.",
    "Inovar é a arte de fazer diferente.",
    "A zona de conforto é o lugar onde os sonhos morrem.",
    "Seja a voz que propõe novas ideias.",
    "A ousadia de criar é o primeiro passo para a mudança.",
    "A curiosidade é o motor da inovação.",
    "Transforme problemas em projetos.",
    "Não limite os seus desafios, desafie os seus limites.",
    "A melhor forma de ter uma boa ideia é ter muitas ideias.",
    "A criatividade é contagiosa. Passe adiante.",
    "A inovação é o combustível do sucesso.",
    "Não se acomode. Busque sempre novas soluções.",
    "O futuro pertence àqueles que criam.",
    "A imaginação é a chave para o progresso.",
    "A inovação começa com a vontade de melhorar.",
    "Questione o status quo.",
    "Não tenha medo de falhar, tenha medo de não aprender.",
    "O próximo grande avanço começa com uma ideia ousada.",
    "Use a criatividade para resolver problemas.",
    "A inovação é a força que impulsiona o nosso crescimento.",
    "Olhe para o mundo de uma forma diferente.",
    "A melhor maneira de prever o futuro é inventá-lo.",
    "Ouse sonhar, ouse fazer.",
    "A inovação é um processo, não um evento.",
    "A criatividade é a base da nossa evolução.",
    "Sua única limitação é a sua imaginação.",
    "A persistência é o caminho do êxito.",
    "Não desista. O começo é sempre a parte mais difícil.",
    "Errar é humano, aprender com o erro é evoluir.",
    "Grandes coisas nunca vêm de zonas de conforto.",
    "Acredite em si mesmo, você é mais capaz do que pensa.",
    "A resiliência é a arte de transformar a dor em poder.",
    "O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.",
    "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
    "A cada dificuldade superada, uma nova força é construída.",
    "A coragem é a resistência ao medo, o domínio do medo, não a ausência do medo.",
    "A vida é 10% do que nos acontece e 90% de como reagimos a isso.",
    "Seja a sua melhor versão, todos os dias.",
    "O crescimento pessoal é a base do sucesso profissional.",
    "Não se compare com os outros, compare-se com o que você era ontem.",
    "A sua atitude determina a sua altitude.",
    "O esforço é a chave para o seu potencial.",
    "O sucesso não é definitivo, o fracasso não é fatal: o que conta é a coragem para continuar.",
    "O que você faz hoje é o que molda o seu futuro.",
    "A perseverança é a mãe do êxito.",
    "Não há crescimento sem desconforto.",
    "Acredite no poder da sua própria história.",
    "A vida é um constante aprendizado.",
    "O que não te desafia, não te transforma.",
    "A sua mente é o seu maior poder.",
    "A melhor maneira de aprender é fazendo.",
    "Não se limite pelas expectativas dos outros.",
    "O seu potencial é ilimitado.",
    "A resiliência é a capacidade de se recuperar rapidamente de dificuldades.",
    "O crescimento é o resultado de uma escolha.",
    "Liderar é inspirar, não impor.",
    "Seja a mudança que você quer ver no mundo.",
    "Uma atitude positiva transforma qualquer ambiente.",
    "Aja como se o que você faz fizesse a diferença, porque faz.",
    "Comece onde você está. Use o que você tem. Faça o que você pode.",
    "Não seja apenas bom no que faz, seja o melhor.",
    "A atitude é a pequena coisa que faz uma grande diferença.",
    "Aja com integridade e inspire confiança.",
    "Um líder é aquele que sabe o caminho, segue o caminho e mostra o caminho.",
    "Não espere por permissão, lidere pelo exemplo.",
    "A verdadeira liderança não é sobre ter seguidores, mas sobre criar novos líderes.",
    "A humildade é uma das maiores qualidades de um líder.",
    "Um líder é um solucionador de problemas.",
    "Não levante a sua voz, melhore o seu argumento.",
    "A liderança é sobre influenciar, não controlar.",
    "O líder inspira a ação.",
    "O seu exemplo é o seu melhor sermão.",
    "A liderança é a arte de motivar as pessoas a fazerem o que precisam ser feito.",
    "Ser líder é assumir a responsabilidade.",
    "A atitude é tudo.",
    "O verdadeiro teste de um líder é a sua capacidade de inspirar e guiar.",
    "A liderança não é um título, é uma ação.",
    "Trate as pessoas como elas são e elas continuarão a ser assim. Trate-as como elas podem ser e elas se tornarão o que podem ser.",
    "Seja a luz, não o julgamento.",
    "A atitude é uma escolha.",
    "A sua paixão é a sua força.",
    "A sua palavra é a sua reputação.",
    "A liderança é sobre ser um guia, não um chefe.",
    "Faça com que os outros se sintam importantes.",
    "A atitude é o pincel com o qual você pinta a sua vida.",
    "O sucesso não é final, o fracasso não é fatal: é a coragem de continuar que conta.",
    "Não subestime o poder de um desafio.",
    "A maior glória na vida não está em nunca cair, mas em levantar-se cada vez que caímos.",
    "As dificuldades preparam pessoas comuns para destinos extraordinários.",
    "O que não te mata, te fortalece.",
    "O sucesso é o resultado de ir de fracasso em fracasso sem perder o entusiasmo.",
    "O desafio é o tempero da vida.",
    "O verdadeiro valor de uma pessoa não está em quanto ela faz, mas em quanto ela supera.",
    "A resiliência é a arte de se adaptar à mudança.",
    "Não fuja dos desafios, enfrente-os.",
    "A superação é a força que te leva ao próximo nível.",
    "Cada desafio é uma oportunidade de aprendizado.",
    "O seu potencial é revelado quando você é testado.",
    "O que parece impossível hoje, amanhã será a sua história de sucesso.",
    "O sucesso é feito de 99% de esforço e 1% de inspiração.",
    "A coragem não é a ausência de medo, mas a capacidade de agir apesar dele.",
    "O seu maior obstáculo pode se tornar o seu maior triunfo.",
    "Não se lamente, trabalhe.",
    "O fracasso é a oportunidade de começar de novo, só que com mais experiência.",
    "Os desafios são oportunidades disfarçadas.",
    "A superação é a prova de que você é mais forte do que pensava.",
    "O que te desafia hoje, te prepara para o amanhã.",
    "A força não vem da vitória. Ela vem da luta.",
    "O que importa é como você lida com as dificuldades, não o quão difícil elas são.",
    "A superação é a prova de que você é capaz.",
    "Transforme a sua dor em poder.",
    "A vida te testa, mas você decide se você falha ou supera.",
    "A verdadeira vitória é a superação pessoal.",
    "Não se curve diante dos desafios.",
    "A superação é a chave para o seu crescimento.",
    "O seu trabalho faz a diferença.",
    "A sua dedicação é a nossa inspiração.",
    "Valorize cada pequena vitória.",
    "A gratidão é o maior reconhecimento.",
    "O sucesso é o resultado de um trabalho bem-feito.",
    "O seu esforço é a base do nosso sucesso.",
    "O reconhecimento é a recompensa pelo trabalho duro.",
    "O que você faz hoje é importante.",
    "A sua contribuição é essencial para o nosso time.",
    "O seu talento é o nosso maior ativo.",
    "O seu empenho é o que nos move.",
    "O sucesso é o resultado de pessoas que fazem o que amam.",
    "A sua dedicação é a nossa força.",
    "O seu trabalho é a prova do seu valor.",
    "O sucesso é um reflexo do seu esforço.",
    "A sua paixão é o que nos inspira.",
    "O seu profissionalismo é a nossa marca.",
    "O seu talento é a nossa maior vantagem.",
    "O reconhecimento é o que nos impulsiona a ir além.",
    "A sua contribuição é o que nos torna um time.",
    "O seu trabalho é o nosso futuro.",
    "A sua dedicação é o nosso maior patrimônio.",
    "O sucesso é a prova do seu trabalho.",
    "O seu valor é inestimável.",
    "O seu esforço é o que nos torna fortes.",
    "A sua dedicação é a nossa maior conquista.",
    "O seu trabalho é a nossa inspiração.",
    "A sua contribuição é o que nos move.",
    "O seu talento é o que nos diferencia.",
    "O seu sucesso é o nosso sucesso.",
    "Uma visão sem ação é apenas um sonho.",
    "O sucesso é o resultado de uma visão clara e um plano de ação.",
    "A sua visão é o seu destino.",
    "A visão é a arte de ver o invisível.",
    "A sua visão é a bússola que guia o seu trabalho.",
    "A melhor maneira de alcançar as suas metas é começar a trabalhar nelas.",
    "As suas metas são o seu guia.",
    "O sucesso é o resultado de metas bem definidas.",
    "A sua visão é o que move a nossa equipe.",
    "A visão é o futuro que queremos criar.",
    "O sucesso é o resultado de uma visão e de um compromisso.",
    "A sua visão é o que te faz acordar todos os dias.",
    "A visão é o que nos inspira a ir além.",
    "O sucesso é a realização das suas metas.",
    "A sua visão é o seu legado.",
    "A visão é o que nos guia para o futuro.",
    "O sucesso é o resultado de uma visão compartilhada.",
    "A sua visão é o que nos torna um time.",
    "A visão é o que nos move para a inovação.",
    "O sucesso é a prova de que a sua visão era a certa.",
    "O futuro pertence àqueles que acreditam na beleza de seus sonhos.",
    "A visão é o que nos impulsiona a crescer.",
    "A sua visão é o que nos une.",
    "O sucesso é o resultado de um plano e de uma execução.",
    "A visão é a nossa luz no fim do túnel.",
    "A sua visão é o que nos faz melhores.",
    "O sucesso é o resultado de uma visão e de uma paixão.",
    "A visão é o que nos move para o próximo nível.",
    "A sua visão é o que nos inspira a ser o melhor.",
    "O sucesso é a prova de que a sua visão era possível.",
    "A perseverança é a mãe do êxito.",
    "O sucesso é o resultado de não desistir.",
    "A motivação é o que te faz começar, o hábito é o que te faz continuar.",
    "A persistência é a chave para o sucesso.",
    "O que te move é a sua motivação.",
    "O sucesso é o resultado de uma mente motivada.",
    "A motivação é a força que te leva a ir além.",
    "Não pare quando estiver cansado, pare quando tiver terminado.",
    "A motivação é o combustível da sua jornada.",
    "O sucesso é o resultado de uma perseverança incansável.",
    "A sua motivação é a nossa inspiração.",
    "A persistência é o que nos diferencia.",
    "O sucesso é o resultado de uma motivação constante.",
    "A motivação é o que nos faz superar os desafios.",
    "O sucesso é a prova de que a sua perseverança valeu a pena.",
    "A motivação é a sua força interna.",
    "A perseverança é a sua maior virtude.",
    "O sucesso é o resultado de uma motivação e de um esforço.",
    "A motivação é o que te faz lutar.",
    "A perseverança é a chave para o sucesso duradouro.",
    "O sucesso é o resultado de uma motivação e de uma paixão.",
    "A motivação é o que te faz ser o melhor.",
    "A perseverança é o que nos torna fortes.",
    "O sucesso é o resultado de uma motivação e de uma dedicação.",
    "A motivação é o que nos move para o futuro.",
    "A perseverança é o que nos inspira a ir além.",
    "O sucesso é o resultado de uma motivação e de uma visão.",
    "A motivação é a sua arma secreta.",
    "A perseverança é a chave para o seu sucesso.",
    "O sucesso é a prova de que a sua motivação era a certa.",
    "Acredite em si mesmo, você é mais capaz do que pensa.",
    "A confiança em si mesmo é o primeiro segredo do sucesso.",
    "A autoconfiança é a chave para o sucesso.",
    "A sua confiança é o seu poder.",
    "Acredite no seu potencial.",
    "A confiança é a base de um bom trabalho.",
    "A sua autoconfiança é a sua maior força.",
    "O sucesso é o resultado de uma confiança inabalável.",
    "Acredite nas suas ideias.",
    "A autoconfiança é a chave para o seu sucesso.",
    "A sua confiança é o que nos move.",
    "O sucesso é o resultado de uma confiança e de um trabalho.",
    "A autoconfiança é o que te faz ir além.",
    "Acredite na sua capacidade.",
    "A confiança é o que nos faz melhores.",
    "O sucesso é o resultado de uma confiança e de uma dedicação.",
    "A autoconfiança é a nossa inspiração.",
    "Acredite no seu talento.",
    "A confiança é o que nos une.",
    "O sucesso é a prova de que a sua autoconfiança era a certa.",
    "A autoconfiança é o que te faz lutar.",
    "Acredite na sua paixão.",
    "A confiança é o que nos move para o futuro.",
    "O sucesso é o resultado de uma autoconfiança e de uma visão.",
    "A autoconfiança é o que nos inspira a ser o melhor.",
    "Acredite no seu potencial.",
    "A confiança é a chave para o seu sucesso.",
    "O sucesso é a prova de que a sua autoconfiança era possível.",
    "A autoconfiança é a base da nossa evolução.",
    "A sua confiança é o que nos diferencia.",
    "O aprendizado é o único que a mente nunca se cansa, nunca tem medo e nunca se arrepende.",
    "O sucesso é o resultado de um aprendizado contínuo.",
    "O conhecimento é o seu maior poder.",
    "Aprenda algo novo todos os dias.",
    "O desenvolvimento pessoal é a chave para o sucesso profissional.",
    "O sucesso é o resultado de um aprendizado e de uma prática.",
    "O aprendizado é o que nos move para o futuro.",
    "O conhecimento é a sua maior ferramenta.",
    "O sucesso é o resultado de um aprendizado e de uma aplicação.",
    "O aprendizado é a sua maior virtude.",
    "O sucesso é o resultado de um aprendizado e de uma persistência.",
    "O aprendizado é o que nos faz melhores.",
    "O conhecimento é a base da nossa evolução.",
    "O sucesso é o resultado de um aprendizado e de uma dedicação.",
    "O aprendizado é o que nos move para a inovação.",
    "O conhecimento é a nossa luz no fim do túnel.",
    "O sucesso é o resultado de um aprendizado e de uma visão.",
    "O aprendizado é o que nos inspira a ir além.",
    "O conhecimento é a sua arma secreta.",
    "O sucesso é a prova de que o seu aprendizado valeu a pena.",
    "O aprendizado é a chave para o seu crescimento.",
    "O conhecimento é o que nos torna fortes.",
    "O sucesso é o resultado de um aprendizado e de uma paixão.",
    "O aprendizado é o que te faz ser o melhor.",
    "O conhecimento é o que nos diferencia.",
    "O sucesso é a prova de que o seu aprendizado era a nossa inspiração.",
    "O aprendizado é o que nos une.",
    "O conhecimento é o que nos move.",
    "O sucesso é o resultado de um aprendizado e de um compromisso.",
    "O aprendizado é o que nos faz ser o que somos.",
    "A gratidão transforma o que temos em suficiente.",
    "O sucesso é o resultado de uma atitude positiva.",
    "A gratidão é o que nos move.",
    "Uma atitude positiva é contagiosa.",
    "A gratidão é o que nos torna mais felizes.",
    "O sucesso é o resultado de uma mente grata.",
    "A gratidão é o que nos inspira.",
    "A positividade é a chave para o sucesso.",
    "A gratidão é o que nos une.",
    "O sucesso é o resultado de uma atitude positiva e de um trabalho.",
    "A gratidão é a nossa força.",
    "A positividade é o que nos faz ir além.",
    "A gratidão é o que nos faz melhores.",
    "O sucesso é o resultado de uma atitude positiva e de uma dedicação.",
    "A gratidão é o que nos move para o futuro.",
    "A positividade é a nossa inspiração.",
    "A gratidão é o que nos inspira a ir além.",
    "O sucesso é o resultado de uma atitude positiva e de uma visão.",
    "A gratidão é a sua arma secreta.",
    "O sucesso é a prova de que a sua atitude positiva era a certa.",
    "A gratidão é a chave para o seu sucesso.",
    "A positividade é o que nos torna fortes.",
    "O sucesso é o resultado de uma atitude positiva e de uma paixão.",
    "A gratidão é o que te faz ser o melhor.",
    "A positividade é o que nos diferencia.",
    "O sucesso é a prova de que a sua atitude positiva era a nossa inspiração.",
    "A gratidão é o que nos une.",
    "A positividade é o que nos move.",
    "O sucesso é o resultado de uma atitude positiva e de um compromisso.",
    "A gratidão é o que nos faz ser o que somos."
];

function exibirFraseDoDia() {
    const fraseDoDiaElemento = document.getElementById("frase-do-dia");
    const dataAtual = new Date().toDateString();
    
    const dataSalva = localStorage.getItem("dataFrase");
    const fraseSalva = localStorage.getItem("fraseDoDia");

    let fraseParaExibir;

    if (dataSalva !== dataAtual) {
        const indiceAleatorio = Math.floor(Math.random() * frases.length);
        fraseParaExibir = frases[indiceAleatorio];

        localStorage.setItem("dataFrase", dataAtual);
        localStorage.setItem("fraseDoDia", fraseParaExibir);
    } else {
        fraseParaExibir = fraseSalva;
    }
    
    if (fraseDoDiaElemento) {
        fraseDoDiaElemento.textContent = fraseParaExibir;
    }
}

document.addEventListener("DOMContentLoaded", exibirFraseDoDia);